flowchart TD
    A[Ruimte en assessment planning] --> B[Planning informatie vanuit Webroom]
    B --> C[Excel overzicht met datum, tijd, duur, module, locatie en docent]
    C --> D[regisseur bereidt registratiemomenten voor]
    D --> E[Aanmaken Brightspace group als tijdslot]
    E --> F[Studenten registreren voor een tijdslot door joinen van een groep]
    F --> G[Docent bekijkt elke groep, om tot een overzicht te komen]
    G --> H[Publicatie overzicht]
    H --> I[Afname assessments]